# -*- coding: utf-8 -*-
"""Final project_Trần Thuý Quỳnh_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYX_Jn-IjUdimUVA6Cdnp9pbDog2r9R-
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

DATA_PATH = "/content/ecommerce_retail.xlsx"
OUTPUT_EXCEL = "rfm_outputs_final.xlsx"

# 2. LOAD & CLEAN DATA
# =========================
def load_and_clean_data(path):
    df = pd.read_excel(path)
    df.columns = df.columns.str.strip()

    # Drop missing CustomerID
    df = df.dropna(subset=["CustomerID"])
    df["CustomerID"] = df["CustomerID"].astype(str)

    # Remove cancelled invoices
    df = df[~df["InvoiceNo"].astype(str).str.startswith("C")]

    # Keep valid purchases
    df = df[(df["Quantity"] > 0) & (df["UnitPrice"] > 0)]

    # Parse datetime
    df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], errors="coerce")
    df = df.dropna(subset=["InvoiceDate"])

    # Transaction amount
    df["Amount"] = df["Quantity"] * df["UnitPrice"]

    return df

df = load_and_clean_data(DATA_PATH)

# 3. BUILD RFM METRICS
# =========================
def build_rfm(df, snapshot_date):
    rfm = df.groupby("CustomerID").agg(
        LastPurchaseDate=("InvoiceDate", "max"),
        Frequency=("InvoiceNo", "nunique"),
        Monetary=("Amount", "sum")
    ).reset_index()

    rfm["Recency"] = (snapshot_date - rfm["LastPurchaseDate"]).dt.days

    return rfm


rfm = build_rfm(df, SNAPSHOT_DATE)

# 4. RFM SCORING (QUINTILE)
# =========================
rfm["R_score"] = pd.qcut(
    rfm["Recency"].rank(method="first"),
    5,
    labels=[5, 4, 3, 2, 1]
).astype(int)

rfm["F_score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

rfm["M_score"] = pd.qcut(
    rfm["Monetary"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

rfm["RFM_Code"] = (
    rfm["R_score"].astype(str)
    + rfm["F_score"].astype(str)
    + rfm["M_score"].astype(str)
)

rfm["RFM_Total"] = rfm[["R_score", "F_score", "M_score"]].sum(axis=1)

# =========================
# 5. PRIMARY COUNTRY & MARKET SPLIT
# =========================
primary_country = (
    df.groupby(["CustomerID", "Country"])["Amount"]
      .sum()
      .reset_index()
      .sort_values(["CustomerID", "Amount"], ascending=[True, False])
      .drop_duplicates("CustomerID")
      .rename(columns={"Country": "PrimaryCountry"})
)

rfm = rfm.merge(primary_country[["CustomerID", "PrimaryCountry"]], on="CustomerID")

rfm["Market"] = np.where(
    rfm["PrimaryCountry"] == "United Kingdom",
    "UK",
    "Non-UK"
)

# 6. SEGMENT MAPPING
def map_segment(rfm_code):
    if rfm_code.startswith("5"):
        return "Champions"
    elif rfm_code.startswith("4"):
        return "Loyal"
    elif rfm_code.startswith("3"):
        return "Potential Loyalist"
    elif rfm_code.startswith("2"):
        return "At Risk"
    else:
        return "Lost"

rfm["Segment"] = rfm["RFM_Code"].apply(map_segment)

# 7. BEHAVIORAL PROFILING
# =========================
order_level = df.groupby(["CustomerID", "InvoiceNo"]).agg(
    OrderAmount=("Amount", "sum"),
    Items=("Quantity", "sum"),
    DistinctSKU=("StockCode", "nunique")
).reset_index()

customer_profile = order_level.groupby("CustomerID").agg(
    TotalOrders=("InvoiceNo", "nunique"),
    TotalRevenue=("OrderAmount", "sum"),
    AOV=("OrderAmount", "mean"),
    ItemsPerOrder=("Items", "mean"),
    SKUperOrder=("DistinctSKU", "mean")
).reset_index()

rfm = rfm.merge(customer_profile, on="CustomerID")

rfm

# 8. SEGMENT PROFILING TABLE
segment_profile = rfm.groupby(["Market", "Segment"]).agg(
    Customers=("CustomerID", "nunique"),
    Revenue=("TotalRevenue", "sum"),
    Avg_AOV=("AOV", "mean"),
    Avg_Items=("ItemsPerOrder", "mean"),
    Avg_SKU=("SKUperOrder", "mean"),
    Avg_Recency=("Recency", "mean")
).reset_index()

# 9. VISUALIZATION
plt.figure(figsize=(12,5))
sns.countplot(data=rfm, x="Segment", hue="Market")
plt.title("Customer Segment Distribution (UK vs Non-UK)")
plt.show()

plt.figure(figsize=(12,5))
sns.boxplot(data=rfm, x="Segment", y="AOV", hue="Market")
plt.title("AOV by Segment (UK vs Non-UK)")
plt.show()

# Heatmap R/F/M score trung bình theo Segment
rfm_scores_heat = (
    rfm.groupby(["Market", "Segment"])[["R_score", "F_score", "M_score"]]
       .mean()
       .reset_index()
)

for market in rfm_scores_heat["Market"].unique():
    sub = rfm_scores_heat[rfm_scores_heat["Market"] == market].copy()
    heat = sub.set_index("Segment")[["R_score", "F_score", "M_score"]]

    plt.figure(figsize=(8, max(4, int(0.6 * len(heat)))))
    sns.heatmap(heat, annot=True, fmt=".2f")
    plt.title(f"Average R/F/M Scores by Segment ({market})")
    plt.xlabel("RFM Scores")
    plt.ylabel("Segment")
    plt.tight_layout()
    plt.show()

with pd.ExcelWriter(OUTPUT_EXCEL, engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name="Clean_Transactions", index=False)
    rfm.to_excel(writer, sheet_name="RFM_Customers", index=False)
    segment_profile.to_excel(writer, sheet_name="Segment_Profile", index=False)